export * from "./MovieDescription";
export * from "./MovieCard";
export * from "./DescriptionTextPhone";
export * from "./Foother";
export * from "./Popular";
export * from "./TopRated";
export * from "./Upcoming";
export * from "./DescriptionTextDesktop";
export * from "./Header-new";
